import { Category } from './types';

export const CATEGORIES: Category[] = [
  {
    id: 'greetings',
    label: 'Greetings & Phrases',
    emoji: '👋',
    description: 'Common greetings and everyday phrases',
    seedPhrases: [
      { phrase: 'hola', translation: 'hello' },
      { phrase: 'buenos días', translation: 'good morning' },
      { phrase: 'buenas noches', translation: 'good night' },
      { phrase: 'por favor', translation: 'please' },
      { phrase: 'gracias', translation: 'thank you' },
      { phrase: 'de nada', translation: 'you\'re welcome' },
      { phrase: 'lo siento', translation: 'I\'m sorry' },
      { phrase: 'con permiso', translation: 'excuse me' },
      { phrase: 'mucho gusto', translation: 'nice to meet you' },
      { phrase: 'hasta luego', translation: 'see you later' },
    ],
  },
  {
    id: 'food',
    label: 'Food & Drink',
    emoji: '🍕',
    description: 'Vocabulary for food, drinks, and dining',
    seedPhrases: [
      { phrase: 'el desayuno', translation: 'breakfast' },
      { phrase: 'el almuerzo', translation: 'lunch' },
      { phrase: 'la cena', translation: 'dinner' },
      { phrase: 'el agua', translation: 'water' },
      { phrase: 'el vino', translation: 'wine' },
      { phrase: 'la cerveza', translation: 'beer' },
      { phrase: 'el café', translation: 'coffee' },
      { phrase: 'el pan', translation: 'bread' },
      { phrase: 'la ensalada', translation: 'salad' },
      { phrase: 'el postre', translation: 'dessert' },
      { phrase: 'la cuenta', translation: 'the bill' },
      { phrase: 'tengo hambre', translation: 'I\'m hungry' },
    ],
  },
  {
    id: 'taste',
    label: 'Taste & Texture',
    emoji: '🍽️',
    description: 'Adjectives describing taste, texture, and flavor',
    seedPhrases: [
      { phrase: 'delicioso', translation: 'delicious' },
      { phrase: 'picante', translation: 'spicy' },
      { phrase: 'dulce', translation: 'sweet' },
      { phrase: 'amargo', translation: 'bitter' },
      { phrase: 'salado', translation: 'salty' },
      { phrase: 'ácido', translation: 'sour' },
      { phrase: 'crujiente', translation: 'crunchy' },
      { phrase: 'suave', translation: 'smooth/soft' },
      { phrase: 'fresco', translation: 'fresh' },
      { phrase: 'asqueroso', translation: 'disgusting' },
      { phrase: 'sabroso', translation: 'tasty' },
    ],
  },
  {
    id: 'emotions',
    label: 'Emotions & Feelings',
    emoji: '😄',
    description: 'Words to express feelings and emotions',
    seedPhrases: [
      { phrase: 'feliz', translation: 'happy' },
      { phrase: 'triste', translation: 'sad' },
      { phrase: 'enojado', translation: 'angry' },
      { phrase: 'asustado', translation: 'scared' },
      { phrase: 'emocionado', translation: 'excited' },
      { phrase: 'aburrido', translation: 'bored' },
      { phrase: 'sorprendido', translation: 'surprised' },
      { phrase: 'cansado', translation: 'tired' },
      { phrase: 'orgulloso', translation: 'proud' },
      { phrase: 'nervioso', translation: 'nervous' },
      { phrase: 'avergonzado', translation: 'embarrassed' },
    ],
  },
  {
    id: 'verbs',
    label: 'Action Verbs',
    emoji: '🏃',
    description: 'Common action verbs for everyday activities',
    seedPhrases: [
      { phrase: 'correr', translation: 'to run' },
      { phrase: 'caminar', translation: 'to walk' },
      { phrase: 'saltar', translation: 'to jump' },
      { phrase: 'hablar', translation: 'to speak' },
      { phrase: 'escuchar', translation: 'to listen' },
      { phrase: 'leer', translation: 'to read' },
      { phrase: 'escribir', translation: 'to write' },
      { phrase: 'cocinar', translation: 'to cook' },
      { phrase: 'limpiar', translation: 'to clean' },
      { phrase: 'dormir', translation: 'to sleep' },
      { phrase: 'trabajar', translation: 'to work' },
      { phrase: 'jugar', translation: 'to play' },
    ],
  },
  {
    id: 'slang',
    label: 'Slang & Informal',
    emoji: '😎',
    description: 'Casual expressions and colloquial Spanish',
    seedPhrases: [
      { phrase: 'guay', translation: 'cool/great' },
      { phrase: 'tío/tía', translation: 'dude/mate' },
      { phrase: 'qué rollo', translation: 'what a drag/what a bore' },
      { phrase: 'mola', translation: 'it\'s cool/it rocks' },
      { phrase: 'vale', translation: 'okay/alright' },
      { phrase: 'venga', translation: 'come on/let\'s go/okay' },
      { phrase: 'flipar', translation: 'to be amazed/to freak out' },
      { phrase: 'mogollón', translation: 'loads/a ton' },
      { phrase: 'estar hecho polvo', translation: 'to be exhausted/worn out' },
      { phrase: 'qué fuerte', translation: 'no way!/that\'s wild' },
      { phrase: 'me mola mazo', translation: 'I really like it' },
    ],
  },
  {
    id: 'travel',
    label: 'Travel & Directions',
    emoji: '✈️',
    description: 'Essential phrases for travel and navigation',
    seedPhrases: [
      { phrase: 'el aeropuerto', translation: 'the airport' },
      { phrase: 'el hotel', translation: 'the hotel' },
      { phrase: 'la estación', translation: 'the station' },
      { phrase: 'a la derecha', translation: 'to the right' },
      { phrase: 'a la izquierda', translation: 'to the left' },
      { phrase: 'todo recto', translation: 'straight ahead' },
      { phrase: 'el billete', translation: 'the ticket' },
      { phrase: 'el pasaporte', translation: 'the passport' },
      { phrase: '¿dónde está?', translation: 'where is it?' },
      { phrase: 'me he perdido', translation: 'I\'m lost' },
      { phrase: 'el mapa', translation: 'the map' },
    ],
  },
  {
    id: 'family',
    label: 'Family & Relationships',
    emoji: '👨‍👩‍👧',
    description: 'Words for family members and relationships',
    seedPhrases: [
      { phrase: 'la madre', translation: 'mother' },
      { phrase: 'el padre', translation: 'father' },
      { phrase: 'el hermano', translation: 'brother' },
      { phrase: 'la hermana', translation: 'sister' },
      { phrase: 'el abuelo', translation: 'grandfather' },
      { phrase: 'la abuela', translation: 'grandmother' },
      { phrase: 'el esposo', translation: 'husband' },
      { phrase: 'la esposa', translation: 'wife' },
      { phrase: 'el hijo', translation: 'son' },
      { phrase: 'la hija', translation: 'daughter' },
      { phrase: 'el novio', translation: 'boyfriend' },
      { phrase: 'la novia', translation: 'girlfriend' },
    ],
  },
  {
    id: 'work',
    label: 'Work & School',
    emoji: '💼',
    description: 'Vocabulary for professional and academic settings',
    seedPhrases: [
      { phrase: 'la reunión', translation: 'the meeting' },
      { phrase: 'el jefe', translation: 'the boss' },
      { phrase: 'el proyecto', translation: 'the project' },
      { phrase: 'la clase', translation: 'the class' },
      { phrase: 'el examen', translation: 'the exam' },
      { phrase: 'el informe', translation: 'the report' },
      { phrase: 'la empresa', translation: 'the company' },
      { phrase: 'el salario', translation: 'the salary' },
      { phrase: 'el plazo', translation: 'the deadline' },
      { phrase: 'la entrevista', translation: 'the interview' },
    ],
  },
  {
    id: 'colors',
    label: 'Colors & Adjectives',
    emoji: '🎨',
    description: 'Colors and descriptive adjectives',
    seedPhrases: [
      { phrase: 'rojo', translation: 'red' },
      { phrase: 'azul', translation: 'blue' },
      { phrase: 'verde', translation: 'green' },
      { phrase: 'amarillo', translation: 'yellow' },
      { phrase: 'negro', translation: 'black' },
      { phrase: 'blanco', translation: 'white' },
      { phrase: 'grande', translation: 'big' },
      { phrase: 'pequeño', translation: 'small' },
      { phrase: 'bonito', translation: 'pretty' },
      { phrase: 'feo', translation: 'ugly' },
      { phrase: 'rápido', translation: 'fast' },
      { phrase: 'lento', translation: 'slow' },
    ],
  },
  {
    id: 'numbers',
    label: 'Numbers & Time',
    emoji: '🔢',
    description: 'Numbers, time expressions, and dates',
    seedPhrases: [
      { phrase: 'mañana', translation: 'tomorrow/morning' },
      { phrase: 'ayer', translation: 'yesterday' },
      { phrase: 'ahora', translation: 'now' },
      { phrase: 'siempre', translation: 'always' },
      { phrase: 'nunca', translation: 'never' },
      { phrase: 'a veces', translation: 'sometimes' },
      { phrase: 'el mediodía', translation: 'noon' },
      { phrase: 'la medianoche', translation: 'midnight' },
      { phrase: '¿qué hora es?', translation: 'what time is it?' },
      { phrase: 'hace un momento', translation: 'a moment ago' },
    ],
  },
  {
    id: 'nature',
    label: 'Nature & Weather',
    emoji: '🌿',
    description: 'Words about the natural world and weather',
    seedPhrases: [
      { phrase: 'el sol', translation: 'the sun' },
      { phrase: 'la lluvia', translation: 'the rain' },
      { phrase: 'la nieve', translation: 'the snow' },
      { phrase: 'el viento', translation: 'the wind' },
      { phrase: 'el árbol', translation: 'the tree' },
      { phrase: 'la montaña', translation: 'the mountain' },
      { phrase: 'el mar', translation: 'the sea' },
      { phrase: 'hace calor', translation: 'it\'s hot' },
      { phrase: 'hace frío', translation: 'it\'s cold' },
      { phrase: 'está nublado', translation: 'it\'s cloudy' },
      { phrase: 'la tormenta', translation: 'the storm' },
    ],
  },
  {
    id: 'home',
    label: 'Home & Objects',
    emoji: '🏠',
    description: 'Household items and rooms',
    seedPhrases: [
      { phrase: 'la cocina', translation: 'the kitchen' },
      { phrase: 'el dormitorio', translation: 'the bedroom' },
      { phrase: 'el baño', translation: 'the bathroom' },
      { phrase: 'la sala', translation: 'the living room' },
      { phrase: 'la silla', translation: 'the chair' },
      { phrase: 'la mesa', translation: 'the table' },
      { phrase: 'la cama', translation: 'the bed' },
      { phrase: 'la ventana', translation: 'the window' },
      { phrase: 'la puerta', translation: 'the door' },
      { phrase: 'el espejo', translation: 'the mirror' },
    ],
  },
  {
    id: 'shopping',
    label: 'Shopping & Money',
    emoji: '🛒',
    description: 'Vocabulary for shopping and financial transactions',
    seedPhrases: [
      { phrase: 'el precio', translation: 'the price' },
      { phrase: 'caro', translation: 'expensive' },
      { phrase: 'barato', translation: 'cheap' },
      { phrase: 'el descuento', translation: 'the discount' },
      { phrase: '¿cuánto cuesta?', translation: 'how much does it cost?' },
      { phrase: 'la tienda', translation: 'the store' },
      { phrase: 'la tarjeta de crédito', translation: 'credit card' },
      { phrase: 'el efectivo', translation: 'cash' },
      { phrase: 'el recibo', translation: 'the receipt' },
      { phrase: 'pagar', translation: 'to pay' },
    ],
  },
  {
    id: 'health',
    label: 'Health & Body',
    emoji: '💊',
    description: 'Body parts, health conditions, and medical vocabulary',
    seedPhrases: [
      { phrase: 'me duele', translation: 'it hurts me' },
      { phrase: 'el médico', translation: 'the doctor' },
      { phrase: 'el hospital', translation: 'the hospital' },
      { phrase: 'la cabeza', translation: 'the head' },
      { phrase: 'el estómago', translation: 'the stomach' },
      { phrase: 'la espalda', translation: 'the back' },
      { phrase: 'estoy enfermo', translation: 'I\'m sick' },
      { phrase: 'la fiebre', translation: 'the fever' },
      { phrase: 'el medicamento', translation: 'the medicine' },
      { phrase: 'me siento mal', translation: 'I feel bad' },
    ],
  },
];

export function getCategoryById(id: string): Category | undefined {
  return CATEGORIES.find((c) => c.id === id);
}
